export const flags = {
  Australia: '🇦🇺',
  China: '🇨🇳',
  Japan: '🇯🇵',
  Bahrain: '🇧🇭',
  'United States': '🇺🇸',
  USA: '🇺🇸',
  Canada: '🇨🇦',
  Mexico: '🇲🇽',
  Austria: '🇦🇹',
  Hungary: '🇭🇺',
  Belgium: '🇧🇪',
  Italy: '🇮🇹',
  Singapore: '🇸🇬',
  'United Kingdom': '🇬🇧',
  'Great Britain': '🇬🇧',
  UK: '🇬🇧',
  Azerbaijan: '🇦🇿',
  'Saudi Arabia': '🇸🇦',
  Monaco: '🇲🇨',
  Spain: '🇪🇸',
  Netherlands: '🇳🇱',
  Brazil: '🇧🇷',
  Qatar: '🇶🇦',
  'United Arab Emirates': '🇦🇪',
  UAE: '🇦🇪',
  France: '🇫🇷',
  Germany: '🇩🇪',
  Switzerland: '🇨🇭',
  Argentina: '🇦🇷',
  Turkey: '🇹🇷',
  Russia: '🇷🇺',
  Malaysia: '🇲🇾',
  Korea: '🇰🇷',
  India: '🇮🇳',
  Portugal: '🇵🇹',
  'South Africa': '🇿🇦',
  Morocco: '🇲🇦',
  Sweden: '🇸🇪',
}
