# Prettier 基本配置文件 (.prettierrc.yml)
# 详细选项请参考官方文档：https://prettier.io/docs/en/options.html

# 使用 2 个空格缩进
tabWidth: 2

# 使用空格而不是 tab
useTabs: false

# 语句末尾加分号
semi: false

# 使用单引号而不是双引号
singleQuote: true
